# Qualquer serviço que você deseja executar deve ser definido aqui.
services:
  database:
    image: "postgres:17.6-alpine3.21"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
