# Qualquer serviço que você deseja executar deve ser definido aqui.
services:
  database:
    image: "postgres:17.6-alpine3.21"
    environment:
      POSTGRES_PASSWORD: "local_password"
    ports:
      - "5432:5432"
