name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Puxa o c처digo para dentro do ambiente

      - uses: actions/setup-node@v4 # Configura o Node.js
        with:
          node-version: "lts/hydrogen" # Vers찾o do Node.js

      - run: npm ci
      - run: npm run lint:prettier:check
  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Puxa o c처digo para dentro do ambiente

      - uses: actions/setup-node@v4 # Configura o Node.js
        with:
          node-version: "lts/hydrogen" # Vers찾o do Node.js

      - run: npm ci
      - run: npm run lint:eslint:check
